fullnameOverride: loki
deploymentMode: Distributed

loki:
  analytics:
    reporting_enabled: false
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  distributor: {}
  extraMemberlistConfig: {}
  index_gateway:
    mode: simple
  ingester:
    autoforget_unhealthy: true
    wal:
      flush_on_shutdown: true
  limits_config:
    allow_structured_metadata: true
    ingestion_burst_size_mb: 800
    ingestion_rate_mb: 1000
    max_global_streams_per_user: 0
    max_line_size_truncate: true
    max_query_bytes_read: 1TB
    per_stream_rate_limit: 5M
    query_timeout: 10m
    retention_period: 14d
    shard_streams:
      desired_rate: 3145728
      enabled: true
    volume_enabled: true
  schemaConfig:
    configs:
      - from: 2024-04-01
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h
  pattern_ingester:
    enabled: false
  querier:
    max_concurrent: 16
  query_range: {}
  query_scheduler:
    max_outstanding_requests_per_tenant: 32768
  runtimeConfig: {}

  server:
    grpc_server_max_recv_msg_size: 16777216
    grpc_server_max_send_msg_size: 16777216
    http_server_read_timeout: 10m
    http_server_write_timeout: 10m
  storage_config:
    boltdb_shipper:
      index_gateway_client:
        server_address: '{{ include "loki.indexGatewayAddress" . }}'
    tsdb_shipper:
      active_index_directory: /var/loki/tsdb-index
      cache_location: /var/loki/tsdb-cache
      index_gateway_client:
        server_address: '{{ include "loki.indexGatewayAddress" . }}'
  tenants: []
  tracing:
    enabled: false

write:
  replicas: 0
backend:
  replicas: 0
read:
  replicas: 0

compactor:
  replicas: 1

distributor:
  replicas: 1



gateway:
  enabled: true
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
  replicas: 1
indexGateway:
  maxUnavailable: 1
  replicas: 1
ingester:
  replicas: 1
  zoneAwareReplication:
    enabled: false

bloomBuilder:
  replicas: 0
bloomGateway:
  replicas: 0

minio:
  enabled: true

patternIngester:
  replicas: 0

querier:
  replicas: 1

queryFrontend:
  replicas: 1

queryScheduler:
  enabled: true
  replicas: 1

memcachedExporter:
  enabled: false

chunksCache:
  enabled: false

resultsCache:
  enabled: false

rollout_operator:
  enabled: false

ruler:
  enabled: false
  replicas: 1

lokiCanary:
  enabled: false
  push: false

test:
  enabled: false

monitoring:
  dashboards:
    enabled: ture
  serviceMonitor:
    enabled: true
